name: Rust

on:
  push:
    branches: ["main"]
    paths:
      - "src/**/*"
      - "ui/**/*"
      - "emu/**/*"
      - ".github/workflows/**/*"
  pull_request:
    branches: ["main"]
    paths:
      - "src/**/*"
      - "ui/**/*"
      - "emu/**/*"
      - ".github/workflows/**/*"

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check fmt
        run: cargo fmt --all --check

  test:
    needs: [fmt]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: cargo test --workspace

  lint:
    needs: [fmt, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: |
          cargo clippy --workspace -- -D warnings     \
          -W clippy::complexity                       \
          -W clippy::correctness                      \
          -W clippy::nursery                          \
          -W clippy::perf                             \
          -W clippy::style                            \
          -W clippy::suspicious
